/** Per-page layout metadata carried over from the static template. */
export const PAGE_META = [
  {
    route: "/",
    name: "Home",
    layout: "main",
    bodyClass: "body",
    headerVariant: "fixed",
  },
  { route: "/home-02", name: "HomeV2", layout: "main", bodyClass: "body" },
  { route: "/home-03", name: "HomeV3", layout: "main", bodyClass: "body" },
  {
    route: "/home-04",
    name: "HomeV4",
    layout: "main",
    bodyClass: "body counter-scroll",
  },
  {
    route: "/home-05",
    name: "HomeV5",
    layout: "main",
    bodyClass: "body",
    headerVariant: "style-2",
  },
  {
    route: "/home-06",
    name: "HomeV6",
    layout: "bare",
    bodyClass: "body",
    headerVariant: "fixed",
    showSearchButton: true,
  },
  {
    route: "/property-halfmap-grid",
    name: "PropertyHalfmapGrid",
    layout: "bare",
    bodyClass: "body",
  },
  {
    route: "/property-halfmap-list",
    name: "PropertyHalfmapList",
    layout: "bare",
    bodyClass: "body",
  },
  {
    route: "/topmap-grid",
    name: "TopmapGrid",
    layout: "main",
    bodyClass: "body",
  },
  {
    route: "/topmap-list",
    name: "TopmapList",
    layout: "main",
    bodyClass: "body",
  },
  {
    route: "/sidebar-grid",
    name: "SidebarGrid",
    layout: "main",
    bodyClass: "body",
  },
  {
    route: "/sidebar-list",
    name: "SidebarList",
    layout: "main",
    bodyClass: "body",
  },
  {
    route: "/property-details-v1",
    name: "PropertyDetailsV1",
    layout: "main",
    bodyClass: "body",
  },
  {
    route: "/property-details-v2",
    name: "PropertyDetailsV2",
    layout: "main",
    bodyClass: "body bg-surface",
  },
  {
    route: "/property-details-v3",
    name: "PropertyDetailsV3",
    layout: "main",
    bodyClass: "body",
  },
  {
    route: "/property-details-v4",
    name: "PropertyDetailsV4",
    layout: "main",
    bodyClass: "body",
  },
  { route: "/about-us", name: "AboutUs", layout: "main", bodyClass: "body" },
  {
    route: "/our-service",
    name: "OurService",
    layout: "main",
    bodyClass: "body",
  },
  { route: "/pricing", name: "Pricing", layout: "main", bodyClass: "body" },
  { route: "/contact", name: "Contact", layout: "main", bodyClass: "body" },
  { route: "/faq", name: "Faq", layout: "main", bodyClass: "body" },
  {
    route: "/privacy-policy",
    name: "PrivacyPolicy",
    layout: "main",
    bodyClass: "body",
  },
  { route: "/blog", name: "Blog", layout: "main", bodyClass: "body" },
  { route: "/blog-grid", name: "BlogGrid", layout: "main", bodyClass: "body" },
  {
    route: "/blog-detail",
    name: "BlogDetail",
    layout: "main",
    bodyClass: "body",
  },
  {
    route: "/dashboard",
    name: "Dashboard",
    layout: "dashboard",
    bodyClass: "body bg-surface counter-scroll",
    innerClass: "main-content-inner",
    footerClass: "footer-dashboard",
  },
  {
    route: "/add-property",
    name: "AddProperty",
    layout: "dashboard",
    bodyClass: "body bg-surface",
    innerClass: "main-content-inner",
    footerClass: "footer-dashboard",
  },
  {
    route: "/my-property",
    name: "MyProperty",
    layout: "dashboard",
    bodyClass: "body bg-surface",
    innerClass: "main-content-inner wrap-dashboard-content",
    footerClass: "footer-dashboard",
  },
  {
    route: "/my-favorites",
    name: "MyFavorites",
    layout: "dashboard",
    bodyClass: "body bg-surface",
    innerClass: "main-content-inner",
    footerClass: "footer-dashboard",
  },
  {
    route: "/reviews",
    name: "Reviews",
    layout: "dashboard",
    bodyClass: "body bg-surface",
    innerClass: "main-content-inner",
    footerClass: "footer-dashboard footer-dashboard-2",
  },
  {
    route: "/message",
    name: "Message",
    layout: "dashboard",
    bodyClass: "body bg-surface",
    innerClass: "main-content-inner",
    footerClass: "footer-dashboard footer-dashboard-2",
  },
  {
    route: "/my-profile",
    name: "MyProfile",
    layout: "dashboard",
    bodyClass: "body bg-surface",
    innerClass: "main-content-inner wrap-dashboard-content-2",
    footerClass: "footer-dashboard",
  },
];

export const META_BY_ROUTE = Object.fromEntries(
  PAGE_META.map((page) => [page.route, page]),
);
