/** Per-page layout metadata carried over from the static template. */
export const PAGE_META = [
  {
    route: "/",
    name: "Home",
    layout: "main",
    bodyClass: "body",
    headerVariant: "fixed",
  },
  { route: "/about-us", name: "AboutUs", layout: "main", bodyClass: "body" },
  { route: "/contact", name: "Contact", layout: "main", bodyClass: "body" },
  { route: "/faq", name: "Faq", layout: "main", bodyClass: "body" },
  {
    route: "/privacy-policy",
    name: "PrivacyPolicy",
    layout: "main",
    bodyClass: "body",
  },
  {
    route: "/dashboard",
    name: "Dashboard",
    layout: "dashboard",
    bodyClass: "body bg-surface counter-scroll",
    innerClass: "main-content-inner",
    footerClass: "footer-dashboard",
  },
  {
    route: "/properties",
    name: "Properties",
    layout: "main",
    bodyClass: "body",
  },
  {
    route: "/properties/:id",
    name: "PropertyDetail",
    layout: "main",
    bodyClass: "body",
  },
  {
    route: "/brokers/:id",
    name: "BrokerProfile",
    layout: "main",
    bodyClass: "body",
  },
  {
    route: "/verify-email",
    name: "VerifyEmail",
    layout: "main",
    bodyClass: "body",
  },
  {
    route: "/reset-password",
    name: "ResetPassword",
    layout: "main",
    bodyClass: "body",
  },
  {
    route: "/my-enquiries",
    name: "MyEnquiries",
    layout: "dashboard",
    bodyClass: "body bg-surface",
    innerClass: "main-content-inner",
    footerClass: "footer-dashboard",
  },
  {
    route: "/admin",
    name: "AdminDashboard",
    layout: "dashboard",
    bodyClass: "body bg-surface",
    innerClass: "main-content-inner",
    footerClass: "footer-dashboard",
  },
  {
    route: "/add-property",
    name: "AddProperty",
    layout: "dashboard",
    bodyClass: "body bg-surface",
    innerClass: "main-content-inner",
    footerClass: "footer-dashboard",
  },
  {
    route: "/my-property",
    name: "MyProperty",
    layout: "dashboard",
    bodyClass: "body bg-surface",
    innerClass: "main-content-inner wrap-dashboard-content",
    footerClass: "footer-dashboard",
  },
  {
    route: "/my-favorites",
    name: "MyFavorites",
    layout: "dashboard",
    bodyClass: "body bg-surface",
    innerClass: "main-content-inner",
    footerClass: "footer-dashboard",
  },
  {
    route: "/message",
    name: "Message",
    layout: "dashboard",
    bodyClass: "body bg-surface",
    innerClass: "main-content-inner",
    footerClass: "footer-dashboard footer-dashboard-2",
  },
  {
    route: "/my-profile",
    name: "MyProfile",
    layout: "dashboard",
    bodyClass: "body bg-surface",
    innerClass: "main-content-inner wrap-dashboard-content-2",
    footerClass: "footer-dashboard",
  },
];

export const META_BY_ROUTE = Object.fromEntries(
  PAGE_META.map((page) => [page.route, page]),
);
